### ISSUE TITLE
Postal - No delivery attempts yet.

### ISSUE THREAD

**Issue by laitkor** [postalhq/postal#287] opened 2017-07-29 11:13 UTC
Hi Team,

Our Postal system has sent approx 300000 emails till now. But in that 6000+ emails pending in mail queue and the status is showing "No delivery attempts yet.".  Is there a way to force Postal to resend all Pending emails ? What can be the reason for this and any possible solution ? 

https://www.screencast.com/t/uhAu2hcSb

Thanks

**Comment by willpower232** [comment] 2017-07-29 11:18
Presuming that your system is still sending the messages, how many workers do you have? `postal status` should tell you if you don't already know

You can increase the number of workers in `postal.yml` like so

```
workers:
  quantity: 10
```

**Comment by laitkor** [comment] 2017-07-29 12:03
4 Workers..  Many of the emails has been sent but many emails are still pending from 2-3 days. You can see the received date in screenshot.  Nothing is sending right now as per the send rate showing on dashboard and nothing in logs.

When I am sending new emails, it sending immediately.. but not attempting to send these old emails.

**Comment by Razva** [comment] 2017-08-13 05:23
@laitkor found any fix? I have the same issue.

**Comment by cyberopus** [comment] 2017-08-15 13:17
@laitkor, @Razva, 
We had same issue when server was trying to send via IPv6 smtp addresses and, at same time, IPv6 was not supported by provider, causing connecting issues. Disabling IPv6 resolved issue. Hope this helps.

**Comment by sahilsunesara** [comment] 2017-08-30 08:52
Hi

i have same issue..is there any solution?

**Comment by cyberopus** [comment] 2017-08-30 09:01
@sahilsunesara Ensure this is not caused by IPv6 connecting issues first, that was our case.

**Comment by sahilsunesara** [comment] 2017-09-14 09:30
@cyberopus i am not using IPv6... some email goes and some are in queue and still in queue since a long time approx 20 days

**Comment by vishnus** [comment] 2017-09-21 06:10
Having same issue. One of our webhooks was not working, that caused delivery to be very slow.. There was 90k emails in queue, so disabled it and restarted postal. After that most of the messages out of 100k delivered except for 6k thats still in pending state. No delivery attempts made in last 2-3 days though no other emails are being queued. I have 6 workers. Any solution?

**Comment by vishnus** [comment] 2017-09-21 07:58
I got it fixed. Theres a table called queued_messages. Just make locked_by, locked_at, retry_after to NULL and postal will automatically send them again. There were worker processes that locked the messages which doesnt exist anymore. So it was locked forever.

**Comment by knightbenax** [comment] 2017-11-16 08:20
@vishnus This is in RabbitMQ right?

**Comment by vishnus** [comment] 2017-11-16 10:08
@knightbenax no, its in DB..

**Comment by Manishjodhani** [comment] 2018-02-21 09:33
@vishnus please tell me if default value is already NULL then...and still my mails are in pending state.
then what should i do???

**Comment by vishnus** [comment] 2018-02-21 11:07
@Manishjodhani ideally, it should retry immediately after you restart all postal workers. Also check if they are locked by any process in the same table.

**Comment by vishnus** [comment] 2018-02-21 11:11
@Manishjodhani I see your screenshot posted in the other issue thread (#498). 

Default value of the column might be null.. Do a 
`select * from queued_messages; `

See the columns mentioned in the above comment. It may not be null. So you can update it to null by this query: 
`update queued_messages set locked_by = NULL, locked_at = NULL, retry_after = NULL; `

PS: this will update and make those three columns null for all entries. So do it after double checking the contents of that table.

**Comment by Manishjodhani** [comment] 2018-02-21 11:42
i think it work but not confirm....i will check it again if it work then i will text here.
@vishnus can you tell one more thing how many worker and thread should i used if my server had 32GB RAM..?

**Comment by vishnus** [comment] 2018-02-21 11:56
@Manishjodhani  you can refer to this discussion #290

**Comment by lovelyns** [comment] 2019-05-26 13:34
> I got it fixed. Theres a table called queued_messages. Just make locked_by, locked_at, retry_after to NULL and postal will automatically send them again. There were worker processes that locked the messages which doesnt exist anymore. So it was locked forever.

Hi @vishnus could you please guide me on how to get to the queue messages table?

**Comment by vishnus** [comment] 2019-05-27 09:10
> @Manishjodhani I see your screenshot posted in the other issue thread (#498).
> 
> Default value of the column might be null.. Do a
> `select * from queued_messages; `
> 
> See the columns mentioned in the above comment. It may not be null. So you can update it to null by this query:
> `update queued_messages set locked_by = NULL, locked_at = NULL, retry_after = NULL; `
> 
> PS: this will update and make those three columns null for all entries. So do it after double checking the contents of that table.

@lovelyns Please refer this

**Comment by influenist** [comment] 2019-07-03 11:41
This issue is still present.

**Comment by skob** [comment] 2019-11-16 21:51
maybe it's ok to clear db lock after maybe 2 minutes ?..

**Comment by willpower232** [comment] 2019-11-24 16:14
This problem mainly occurs if your worker processes are stopped unexpectedly so should be a rarity if your servers limits are appropriate and you have enough resources available to meet them.

That said, it could be handy if there was a method for detecting and resolving these "stranded" messages however if this was occurring due to problems with IPv6 then this could cause an infinite loop so would need extra tracking to fail appropriately.

**Comment by jbci** [comment] 2019-12-14 23:00
The issue affects my setup too.
Already checked queued_messages table but all those fields were yet set to NULL.
Any hint on how to solve it? or where to keep investgation from?

**Comment by willpower232** [comment] 2019-12-15 12:22
@jbci if you've used `postal status` to see that everything is running and you're still not sending emails, have a look at your log files and if you have any questions, please open a new issue as you've already confirmed your problem is different to this one

**Closed** 2019-12-15 12:23 UTC
Labels: support

**Comment by fav22** [comment] 2022-01-24 11:37
> I got it fixed. Theres a table called queued_messages. Just make locked_by, locked_at, retry_after to NULL and postal will automatically send them again. There were worker processes that locked the messages which doesnt exist anymore. So it was locked forever.

Hey , i got the same issue but i don't know how to access to this table right now , can you help please ? Thank you

**Comment by influenist** [comment] 2022-01-24 11:40
When/how is this issue going to be fixed? Because this comes back with every installation and hard to monitor seen you need to specifically seen there are no error / bounce messages to the original sender.

**Comment by fav22** [comment] 2022-01-24 11:44
Postal try to send some emails for 1 hour i guess and then stop sending after so all messages are stuck in queud

**Comment by fav22** [comment] 2022-01-24 12:03
This is the result of `service rabbitmq-server status`
`● rabbitmq-server.service - RabbitMQ Messaging Server
     Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-01-24 13:02:09 CET; 183ms ago
    Process: 235511 ExecStart=/usr/sbin/rabbitmq-server (code=exited, status=1/FAILURE)
   Main PID: 235511 (code=exited, status=1/FAILURE)
`

**Comment by HRarsha** [comment] 2025-03-05 17:52
> [@Manishjodhani](https://github.com/Manishjodhani) I see your screenshot posted in the other issue thread ([#498](https://github.com/postalserver/postal/issues/498)).
> 
> Default value of the column might be null.. Do a `select * from queued_messages; `
> 
> See the columns mentioned in the above comment. It may not be null. So you can update it to null by this query: `update queued_messages set locked_by = NULL, locked_at = NULL, retry_after = NULL; `
> 
> PS: this will update and make those three columns null for all entries. So do it after double checking the contents of that table.

Helpful! I had just one on the queue pending without even retiring. Just fixed with this method.  Thank you!

**Comment by hoanguyenchi** [comment] 2026-03-18 03:43
> @Manishjodhani I see your screenshot posted in the other issue thread ([#498](https://github.com/postalserver/postal/issues/498)).
> 
> Default value of the column might be null.. Do a `select * from queued_messages; `
> 
> See the columns mentioned in the above comment. It may not be null. So you can update it to null by this query: `update queued_messages set locked_by = NULL, locked_at = NULL, retry_after = NULL; `
> 
> PS: this will update and make those three columns null for all entries. So do it after double checking the contents of that table.

you saved my day
