### ISSUE TITLE
How to send mail in Postal SMTP by using port 587 or 2525

### ISSUE THREAD

**Issue by itsdevil65** [postalhq/postal#1407] opened 2021-07-14 14:17 UTC
Hey,
My service provider block my port 25. So I got execution expired error.

How can I send by using port 587 or 2525?

Because some person send mail by using port 587.
Anyone help me?

**Comment by willpower232** [comment] 2021-07-14 14:58
duplicate of #1403

**Closed by willpower232** 2021-07-14 14:58 UTC
Labels: duplicate
