### ISSUE TITLE
Webhook not always called

### ISSUE THREAD

**Issue by alexroosenstein** [postalhq/postal#265] opened 2017-07-12 11:09 UTC
We have a webhook configured that's set to receive all events. When sending out larger batches of emails (think of 15k emails in a timeframe of 30 to 60 minutes), we are not receiving a "MessageSent" event for all of these sent emails (we are actually missing around MessageSent events for roughly 7k of the emails)

I even looked directly in the database (table webhook_requests), but I could not find the event for a specific sent email, while I can find others. (I'm searching by using the following SQL query `SELECT * FROM webhook_requests WHERE payload LIKE '%<MESSAGE ID HERE>%';`)

Is this a known problem?

**Comment by adamcooke** [comment] 2017-07-12 20:05
This isn't a known problem.

**Comment by alexroosenstein** [comment] 2017-07-21 13:06
I've been debugging a bit:

I noticed it doesn't actually add the webhook event into the database until after it has been (at least attempted) delivered?

The missing webhook events seem to be processed normally, up until the queue. The [function queue](https://github.com/atech/postal/blob/master/lib/postal/job.rb#L35) is called just fine, but I'm not sure if it's published correctly, or maybe that rabbitmq discards the webhook event?

I'm not really sure where to go from here, any tips on how to debug the actual queue?

**Comment by mackinra** [comment] 2017-08-19 01:28
@adamcooke We seem to be encountering the same issue.  Everything seemed fine while we were ramping up emails on a new IP, until we reached ~7K emails in a day.   While comparing and consolidating the data we have and the data in Postal's `webhook_requests` table, it dawned on me that the contents of `webhook_requests` seems to be where the missing data is.  Can you confirm that the data is purged from this table once it's delivered to our webhook?  

As you can see from the [attached table](https://imagebin.ca/v/3XMdkmzO4v2L), the last two columns are eerily similar suggesting that the `webhook_requests` table houses the missing delivery events our system didn't receive.

**Comment by mackinra** [comment] 2017-08-19 01:31
...and spot-checking a few of the message in the `webhook_requests` payloads, I can confirm that they're missing a delivery date on our end (suggesting the webhook request was never made)!

**Comment by mackinra** [comment] 2017-08-20 07:10
...the other tell-tale sign of a problem is that the `webhook_request.attempts` values are ALL 0, further suggesting that everything in this table has not been sent.

**Comment by playworker** [comment] 2017-09-12 11:23
I am experiencing similar issues - I've not delved into the details but we seem to be missing around 50% of the Sent webhook messages from a batch of ~10k emails, I've received just over 4k webhook messages but over 9k of the messages have a status of Sent in the database

**Comment by shopglobal** [comment] 2017-09-12 11:40
Community,
How can you help us to understand the methods your are using to connect to
the endpoints? Are you displaying clicks and opens on your platform or
postal? (Or both?) What is the objective?

Warm regards

**Comment by shopglobal** [comment] 2017-09-12 11:41
What's the best way to integrate Postal API with esp platform?

Are you transferring your data via SMTP?

**Comment by willpower232** [comment] 2017-09-12 15:24
@shopglobal please read https://github.com/atech/postal/wiki and open a new issue for your questions

**Comment by shopglobal** [comment] 2017-09-12 15:52
Thanks Will

Anything helps

Cheers!

**Closed** 2020-01-09 15:08 UTC
